<?php

	$data = array 	("list" => array(
	
	$data = array	("rank"=> "1",
				  	"name"=> "Dog Days Are Over",
				  	"artist"=> "Florence and the Machine",
				  	"album"=> "Lungs",
				  	"year"=> "2008",
				  	"duration"=> "3:04",
				  	"image"=> "http://upload.wikimedia.org/wikipedia/en/7/75/DogDaysAreOver_F%26M.jpg"),	
				  				  
	$data = array	("rank"=> "2",
				  	"name"=> "Daniel",
				  	"artist"=> "Bat for Lashes",
				  	"album"=> "Two Suns",
				  	"year"=> "2008",
				  	"duration"=> "2:09",
				  	"image"=> "http://blogs.mirror.co.uk/the-ticket/css/Bat%20for%20Lashes.jpg"),
				  					  
	$data = array	("rank"=> "3",
				  	"name"=> "Stem",
				  	"artist"=> "DJ shadow",
				  	"album"=> "Endtroducing",
				  	"year"=> "1996",
				  	"duration"=> "3:10",
				  	"image"=> "http://sleevage.com/wp-content/uploads/2008/03/dj_shadow_outsider_sleevage.jpg"),
				  
	$data = array	("rank"=> "4",
				  	"name"=> "White Chalk",
				  	"artist"=> "PJ Harvey",
				  	"album"=> "White Chalk",
				  	"year"=> "2006",
				  	"duration"=> "2:40",
				  	"image"=> "https://thenoisemadebypeople.files.wordpress.com/2012/03/white-chalk.jpg"),
				  
	$data = array	("rank"=> '5',
					"name"=> 'Reckoner',
					"artist"=> 'RadioHead',
					"album"=> 'In Rainbows',
					"year"=> '2000',
					"duration"=> '3:45',
					"image"=> "http://www.pulsarmedia.eu/data/media/24/Reckoner.jpg"),
					  
	$data =	array	("rank"=> "6",
				  	"name"=> "Londinium",
				  	"artist"=> "Archive",
				  	"album"=> "Tripop",
				  	"year"=> "1996",
				  	"duration"=> "3:00",
				  	"image"=> "http://1.bp.blogspot.com/_enRas4CTFVI/S6sgwRZSAUI/AAAAAAAAAoU/19k0saFHu7Q/s1600/londinium.jpg"),
			
	$data =	array	("rank"=> "7.",
				  	"name" => "Your Silent Face",
				  	"artist" => "New Order",
				  	"album"=> "Power, Corruption & Liesl", 
				  	"year"=> "1983",
				  	"duration"=> "5:09",
				  	"img" => " http://25.media.tumblr.com/tumblr_m6w7a2bVkO1r82709_1341836225_cover.png"),
				  	
	$data =	array	( "rank"=> "8.",
					"name" => "Nas-It Ain't Hard To Tell",
					"artist" => "Dj dangermouse",
					"album"=> "Remix White Label VLS", 
					"year"=> "2007",
					"duration"=> "2:06",
					"img" => " http://farm3.static.flickr.com/2393/2268568084_ba89776a28_o.jpg"),
					
	$data =	array	("rank"=> "9.",
					"name" => "Someone Great",
					"artist" =>"LCD Soundsystem",
					"album"=> "Sound Of Silver", 
					"year"=> "2011",
					"duration"=> "6:00",
					"img" => "http://upload.wikimedia.org/wikipedia/en/d/d2/Someone_great_cover.jpg"),
					
	$data =	array	("rank"=> "10.",
					"name" => "Skinny love",
					"artist" => "Bon Iver",
					"album"=> "For Emma, Forever Ago", 
					"year"=> "2009",
					"duration"=> "3:59",
					"img" => "http://userserve-ak.last.fm/serve/_/10366619/For+Emma+Forever+Ago+New+album+cover.jpg"),
			
	$data =	array	("rank"=> "11.",
					"name" => "ABC",
					"artist" => "Jackson 5",
					"album"=> "ABC", 
					"year"=> "1970",
					"duration"=> "3:31",
					"img" => "http://www.soulstrut.com/images/uploads/reviews/Jackson%20five%20-%20ABC%20%20(1970).JPG.jpeg"),
			
	$data =	array	("rank"=> "12.",
					"name" => "Tiny Daner",
					"artist" => "Elton John",
					"album"=> "Madman Across the Water", 
					"year"=> " 1972",
					"duration"=> "3:59",
					"img" => "http://upload.wikimedia.org/wikipedia/en/3/37/Elton_John_Tiny_Dancer.jpg"),
										
	$data =	array	("rank"=> "13.",
					"name" => "Wrath of God",
					"artist" => "Crystal Castles",
					"album"=> "Third Album", 
					"year"=> "2012",
					"duration"=> "3:07",
					"img" => "http://www.theprophetblog.net/wp-content/uploads/2012/09/Crystal-Castles-Wrath-of-God-III.jpg"),

	$data =	array 	("rank"=> "14.",
					"name" => "Nightcall",
					"artist" => "Kavinsky",
		 			"album"=> "Nightcall", 
					"year"=> "2011",
					"duration"=> "4:00",
					"img" => "http://bravatablog.com/wp-content/uploads/2012/06/kavinsky-nightcall_front.jpg"),
			
	$data =	array	("rank"=> "15.",
					"name" => "Blue Crystal Fire",
					"artist" => "How to Dress Well",
					"album"=> "Total Loss",  
					"year"=> "2012",
					"duration"=> "4:52",
					"img" => "http://cdn4.pitchfork.com/tracks/14389/homepage_large.c5b9093a.jpg"),
			
	$data =	array	("rank"=> "16.",
					"name" => "Salty Air",
					"artist" => "J.Viewz",
					"album"=> "Work in Progress", 
					"year"=> "2010",
					"duration"=> "3:56",
					"img" => "http://1.bp.blogspot.com/_horQT6YBepA/TM-MxvIFSOI/AAAAAAAAATA/H5T3YLHGuug/s1600/0000929693_350.jpg"),
	
	));
	
		
	
?>
